{"name": "test_login_fail", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to have text 'lỗi'\nActual value: <element(s) not found> \nCall log:\nLocatorAssertions.to_have_text with timeout 5000ms\n  - waiting for locator(\".username\")", "trace": "self = <test_login.TestLogin object at 0x0000017DE67CEA50>, page = <Page url='https://hocvancokimngan.com/login/'>\n\n    def test_login_fail(self, page):\n        lp= LoginPage(page)\n        lp.goto().login(settings.USER_EMAIL, \"pasw\")\n>       lp.assert_login_fail(\"lỗi\")\n\ntests\\web\\test_login.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.login_page.LoginPage object at 0x0000017DE7F40920>, username = 'lỗi'\n\n    def assert_login_fail(self, username):\n        with allure.step(\"Xác minh đăng nhập không thành công\"):\n>           expect(self.page.locator(self.lbl_username)).to_have_text(username)\nE           AssertionError: Locator expected to have text 'lỗi'\nE           Actual value: <element(s) not found> \nE           Call log:\nE           LocatorAssertions.to_have_text with timeout 5000ms\nE             - waiting for locator(\".username\")\n\npages\\login_page.py:44: AssertionError"}, "steps": [{"name": "Mở trang chủ", "status": "passed", "start": 1755784142005, "stop": 1755784143220}, {"name": "Đi tới trang Sign in", "status": "passed", "start": 1755784143220, "stop": 1755784143315}, {"name": "Nhập thông tin đăng nhập", "status": "passed", "start": 1755784143315, "stop": 1755784143426}, {"name": "Đăng nhập", "status": "passed", "start": 1755784143426, "stop": 1755784144200}, {"name": "Xác minh đăng nhập không thành công", "status": "failed", "statusDetails": {"message": "AssertionError: Locator expected to have text 'lỗi'\nActual value: <element(s) not found> \nCall log:\nLocatorAssertions.to_have_text with timeout 5000ms\n  - waiting for locator(\".username\")\n\n", "trace": "  File \"C:\\Users\\thanh\\PycharmProjects\\auto_python_playwright_web\\pages\\login_page.py\", line 44, in assert_login_fail\n    expect(self.page.locator(self.lbl_username)).to_have_text(username)\n  File \"C:\\Users\\thanh\\PycharmProjects\\auto_python_playwright_web\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 19324, in to_have_text\n    self._sync(\n  File \"C:\\Users\\thanh\\PycharmProjects\\auto_python_playwright_web\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\thanh\\PycharmProjects\\auto_python_playwright_web\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 481, in to_have_text\n    await self._expect_impl(\n  File \"C:\\Users\\thanh\\PycharmProjects\\auto_python_playwright_web\\.venv\\Lib\\site-packages\\playwright\\_impl\\_assertions.py\", line 74, in _expect_impl\n    raise AssertionError(\n"}, "start": 1755784144200, "stop": 1755784149208}], "start": 1755784141999, "stop": 1755784149216, "uuid": "6507edad-8e85-4cf5-ae6b-9fdba41c6b92", "historyId": "5796fb86233b5d06cf9d5ae4bf3581b2", "testCaseId": "5796fb86233b5d06cf9d5ae4bf3581b2", "fullName": "tests.web.test_login.TestLogin#test_login_fail", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Authentication"}, {"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests.web"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Thanh-PC"}, {"name": "thread", "value": "7580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.web.test_login"}]}